### ISSUE TITLE
Guidance for a custom `code` block

### ISSUE THREAD

**Issue by stokedout** [shunnNet/vue-markdown#1]
Hey, I'm using your package and I'd like to render a custom code block. I've used the following to handle inline vs block.

```
<template #code="{ children, ...props }">
    <code class="v-code" v-if="props.inline">
        <Component :is="children" />
    </code>
    <code-block v-else :value="???" v-bind="props">
        <Component :is="children" />
    </code-block>
</template>
```

The issue is that `code-block` expects the `value` property for say SQL and not `children`. Do you know how I can get the value from children and pass it to `<code-block v-else :value="???"...` ? The trouble is the output is 

```
() => parseChildren(node2.children, thisContext, node2)
```

**Comment by stokedout** [comment]
Answered my own question:

```
...
 <code-block v-else :value="children()" v-bind="props">
...
```

**Comment by shunnNet** [comment]
@stokedout 
Hello, thank you for reporting the issue.

Previously, this use case was not considered, so there was no way to directly extract the content of the code.
I have added this functionality in version `0.3.0`. You can now use `content` to get the text content of the code block.
I have updated the [documentation](https://github.com/shunnNet/vue-markdown?tab=readme-ov-file#doc-scoped-slot-and-custom-attrs) and included a simple example.

Please upgrade and give it a try!
